[package]
name = "bromide"
version = "0.1.0"
authors = ["Deathlesz"]
edition = "2021"
description = "A server software reimplementation for a certain platformer."
readme = "README.md"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
axum = "0.7"
sqlx = { version = "0.7", features = ["macros", "sqlite"] }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
