DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    account_id BIGINT UNIQUE NOT NULL,

    icon_id SMALLINT NOT NULL DEFAULT 1,
    icon_type SMALLINT NOT NULL DEFAULT 0,
    glowing BOOLEAN NOT NULL DEFAULT FALSE,
    primary_color SMALLINT NOT NULL DEFAULT 0,
    secondary_color SMALLINT NOT NULL DEFAULT 3,
    tertiary_color SMALLINT NOT NULL DEFAULT 0,
    cube_id SMALLINT NOT NULL DEFAULT 1,
    ship_id SMALLINT NOT NULL DEFAULT 1,
    ball_id SMALLINT NOT NULL DEFAULT 1,
    ufo_id SMALLINT NOT NULL DEFAULT 1,
    wave_id SMALLINT NOT NULL DEFAULT 1,
    robot_id SMALLINT NOT NULL DEFAULT 1,
    spider_id SMALLINT NOT NULL DEFAULT 1,
    swing_id SMALLINT NOT NULL DEFAULT 1,
    jetpack_id SMALLINT NOT NULL DEFAULT 1,
    glow_id SMALLINT NOT NULL DEFAULT 0,
    explosion_id SMALLINT NOT NULL DEFAULT 1,

    stars BIGINT NOT NULL DEFAULT 0,
    moons BIGINT NOT NULL DEFAULT 0,
    diamonds BIGINT NOT NULL DEFAULT 0,
    secret_coins BIGINT NOT NULL DEFAULT 0,
    user_coins BIGINT NOT NULL DEFAULT 0,
    creator_points BIGINT NOT NULL DEFAULT 0,

    -- TODO: use enums?
    message_state SMALLINT NOT NULL DEFAULT 0,
    friend_state SMALLINT NOT NULL DEFAULT 0,
    comment_history_state SMALLINT NOT NULL DEFAULT 0,

    youtube_url VARCHAR(255) NOT NULL DEFAULT '',
    twitter_url VARCHAR(255) NOT NULL DEFAULT '',
    twitch_url VARCHAR(255) NOT NULL DEFAULT '',

    -- TODO: here too?
    mod_level SMALLINT NOT NULL DEFAULT 0,

    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
)
